test('throws invalid number', async () => {
  //TODO
});

